version: "3.9"
services:
  nest:
    container_name: nest-dev
    build:
      context: ./nest
      dockerfile: Dockerfile
    command: sh -c "yarn install && npm run start:dev" # Ensure node_modules is synced with host
    volumes:
      - ./nest:/app
      - /app/node_modules
    ports:
      - "${NEST_PORT}:${NEST_PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${NEST_PORT}
      - NEXT_URL=${NEXT_URL}
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy

  next:
    container_name: next-dev
    build:
      context: ./next
      dockerfile: Dockerfile
    command: sh -c "yarn install && yarn dev" # Ensure node_modules is synced with host
    volumes:
      - ./next:/app
      - /app/node_modules
    ports:
      - "${NEXT_PORT}:${NEXT_PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${NEXT_PORT}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

  postgres:
    container_name: postgres-dev
    image: postgres:16-alpine
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
